export const GET_TICKETS_LIST = 'GET_TICKETS_LIST';
export const GET_TICKETS_LIST_SUCCESS = 'GET_TICKETS_LIST_SUCCESS';
export const GET_TICKETS_LIST_ERROR = 'GET_TICKETS_LIST_ERROR';

export const GET_TICKETS_CONFIG = 'GET_TICKETS_CONFIG';
export const GET_TICKETS_CONFIG_SUCCESS = 'GET_TICKETS_CONFIG_SUCCESS';
export const GET_TICKETS_CONFIG_ERROR = 'GET_TICKETS_CONFIG_ERROR';

export const ADD_TICKET = 'ADD_TICKET';
export const ADD_TICKET_SUCCESS = 'ADD_TICKET_SUCCESS';
export const ADD_TICKET_ERROR = 'ADD_TICKET_ERROR';

export const GET_TICKET_VIEW = 'GET_TICKET_VIEW';
export const GET_TICKET_VIEW_SUCCESS = 'GET_TICKET_VIEW_SUCCESS';
export const GET_TICKET_VIEW_ERROR = 'GET_TICKET_VIEW_ERROR';

export const SEND_MESSAGE = 'SEND_MESSAGE';
export const SEND_MESSAGE_SUCCESS = 'SEND_MESSAGE_SUCCESS';
export const SEND_MESSAGE_ERROR = 'SEND_MESSAGE_ERROR';

export const UNREAD_MESSAGE = 'UNREAD_MESSAGE';
export const UNREAD_MESSAGE_SUCCESS = 'UNREAD_MESSAGE_SUCCESS';
export const UNREAD_MESSAGE_ERROR = 'UNREAD_MESSAGE_ERROR';

export const CLOSE_TICKET = 'CLOSE_TICKET';
export const CLOSE_TICKET_SUCCESS = 'CLOSE_TICKET_SUCCESS';
export const CLOSE_TICKET_ERROR = 'CLOSE_TICKET_ERROR';

export const DELETE_TICKET = 'DELETE_TICKET';
export const DELETE_TICKET_SUCCESS = 'DELETE_TICKET_SUCCESS';
export const DELETE_TICKET_ERROR = 'DELETE_TICKET_ERROR';

export const DELETE_MESSAGE = 'DELETE_MESSAGE';
export const DELETE_MESSAGE_SUCCESS = 'DELETE_MESSAGE_SUCCESS';
export const DELETE_MESSAGE_ERROR = 'DELETE_MESSAGE_ERROR';

export const CHANGE_MASS_STATUS = 'CHANGE_MASS_STATUS';
export const CHANGE_MASS_STATUS_SUCCESS = 'CHANGE_MASS_STATUS_SUCCESS';
export const CHANGE_MASS_STATUS_ERROR = 'CHANGE_MASS_STATUS_ERROR';

export const CHANGE_TICKET_MESSAGE = 'CHANGE_TICKET_MESSAGE';
export const CHANGE_TICKET_MESSAGE_SUCCESS = 'CHANGE_TICKET_MESSAGE_SUCCESS';
export const CHANGE_TICKET_MESSAGE_ERROR = 'CHANGE_TICKET_MESSAGE_ERROR';

export const CLEAR_TICKET_VIEW = 'CLEAR_TICKET_VIEW';

export const SET_ACTIVE_TICKET_FOR_TICKET_VIEW = 'SET_ACTIVE_TICKET_FOR_TICKET_VIEW';

export const MASS_TICKETS_ASSIGN = 'MASS_TICKETS_ASSIGN';
export const MASS_TICKETS_ASSIGN_SUCCESS = 'MASS_TICKETS_ASSIGN_SUCCESS';
export const MASS_TICKETS_ASSIGN_ERROR = 'MASS_TICKETS_ASSIGN_ERROR';

export const ASSIGN_TICKET = 'ASSIGN_TICKET';
export const ASSIGN_TICKET_SUCCESS = 'ASSIGN_TICKET_SUCCESS';
export const ASSIGN_TICKET_ERROR = 'ASSIGN_TICKET_ERROR';
