export const en = {
  translation: {
    Table: {
      All: 'All',
      ID: 'ID',
      User: 'User',
      'Order ID': 'Order ID',
      'Start count': 'Start count',
      Quantity: 'Quantity',
      'Current count': 'Current count',
      'To refill': 'To refill',
      Service: 'Service',
      Status: 'Status',
      Created: 'Created',
      Mode: 'Mode',
      Empty: '',
      Actions: 'Actions',
      MassCounterRefill: '{{count}} refills selected',
      Fail: 'Fail',
    },
    Navbar: {
      Users: 'Users',
      Orders: 'Orders',
      Subscriptions: 'Subscriptions',
      'Drip-feed': 'Drip-feed',
      Tasks: 'Tasks',
      Refill: 'Refill',
      Cancel: 'Cancel',
      Services: 'Services',
      Payments: 'Payments',
      Tickets: 'Tickets',
      Affiliates: 'Affiliates',
      'Child panels': 'Child panels',
      Reports: 'Reports',
      Appearance: 'Appearance',
      Settings: 'Settings',
      Account: 'Account',
      Logout: 'Logout',
    },
    ActionsList: {
      'Change status': 'Change status',
      Resend: 'Resend',
      Cancel: 'Cancel',
      'Cancel and refund': 'Cancel and refund',
      'In progress': 'In progress',
      Rejected: 'Rejected',
      Details: 'Details',
      'Details for superadmin': 'Details for superadmin',
      Processing: 'Processing',
      Success: 'Success',
      Complete: 'Complete',
    },
    Tabs: {
      All: 'All',
      Awaiting: 'Awaiting',
      Pending: 'Pending',
      'In progress': 'In progress',
      Rejected: 'Rejected',
      Error: 'Error',
      Completed: 'Completed',
      Processing: 'Processing',
      Success: 'Success',
      Canceled: 'Canceled',
      Fail: 'Fail',
    },
    SearchGroup: {
      Placeholder: {
        Search: 'Search',
        'Search users': 'Search users',
        'Search tickets': 'Search tickets',
      },
    },
  },
};
