export const CHANGE_VIEW_MODE = 'CHANGE_VIEW_MODE';
export const CHANGE_VIEW_MODE_SUCCESS = 'CHANGE_VIEW_MODE_SUCCESS';
export const CHANGE_VIEW_MODE_ERROR = 'CHANGE_VIEW_MODE_ERROR';

export const CHECK_AUTORIZATION = 'CHECK_AUTORIZATION';
export const CHECK_AUTORIZATION_SUCCESS = 'CHECK_AUTORIZATION_SUCCESS';
export const CHECK_AUTORIZATION_ERROR = 'CHECK_AUTORIZATION_ERROR';

// Services
export const GET_SERVICES_LIST_ALL = 'GET_SERVICES_LIST_ALL';
export const GET_SERVICES_LIST_ALL_SUCCESS = 'GET_SERVICES_LIST_ALL_SUCCESS';
export const GET_SERVICES_LIST_ALL_ERROR = 'GET_SERVICES_LIST_ALL_ERROR';
