export const GET_USER_DATA = 'GET_USER_DATA';
export const GET_USER_DATA_SUCCESS = 'GET_USER_DATA_SUCCESS';
export const GET_USER_DATA_ERROR = 'GET_USER_DATA_ERROR';

export const CREATE_USER = 'CREATE_USER';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const CREATE_USER_ERROR = 'CREATE_USER_ERROR';

export const UPDATE_USER_DATA = 'UPDATE_USER_DATA';
export const UPDATE_USER_DATA_SUCCESS = 'UPDATE_USER_DATA_SUCCESS';
export const UPDATE_USER_DATA_ERROR = 'UPDATE_USER_DATA_ERROR';

export const GET_USERS_LIST = 'GET_USERS_LIST';
export const GET_USERS_LIST_SUCCESS = 'GET_USERS_LIST_SUCCESS';
export const GET_USERS_LIST_ERROR = 'GET_USERS_LIST_ERROR';

export const CLEAR_USER_DATA = 'CLEAR_USER_DATA';
export const CHANGE_USER_STATUS = 'CHANGE_USER_STATUS';
export const CHANGE_USER_STATUS_SUCCESS = 'CHANGE_USER_STATUS_SUCCESS';
export const CHANGE_USER_STATUS_ERROR = 'CHANGE_USER_STATUS_ERROR';

export const GET_USERS_CONFIGS = 'GET_USERS_CONFIGS';
export const GET_USERS_CONFIGS_SUCCESS = 'GET_USERS_CONFIGS_SUCCESS';
export const GET_USERS_CONFIGS_ERROR = 'GET_USERS_CONFIGS_ERROR';

export const COPY_CUSTOM_RATES = 'COPY_CUSTOM_RATES';
export const COPY_CUSTOM_RATES_SUCCESS = 'COPY_CUSTOM_RATES_SUCCESS';
export const COPY_CUSTOM_RATES_ERROR = 'COPY_CUSTOM_RATES_ERROR';

export const SET_USER_PASSWORD = 'SET_USER_PASSWORD';
export const SET_USER_PASSWORD_SUCCESS = 'SET_USER_PASSWORD_SUCCESS';
export const SET_USER_PASSWORD_ERROR = 'SET_USER_PASSWORD_ERROR';

export const MASS_CHANGE_STATUS = 'MASS_CHANGE_STATUS';
export const MASS_CHANGE_STATUS_SUCCESS = 'MASS_CHANGE_STATUS_SUCCESS';
export const MASS_CHANGE_STATUS_ERROR = 'MASS_CHANGE_STATUS_ERROR';

export const MASS_RESET_RATES = 'MASS_RESET_RATES';
export const MASS_RESET_RATES_SUCCESS = 'MASS_RESET_RATES_SUCCESS';
export const MASS_RESET_RATES_ERROR = 'MASS_RESET_RATES_ERROR';

export const MASS_COPY_RATES = 'MASS_COPY_RATES';
export const MASS_COPY_RATES_SUCCESS = 'MASS_COPY_RATES_SUCCESS';
export const MASS_COPY_RATES_ERROR = 'MASS_COPY_RATES_ERROR';

export const GET_USERS_WITH_CUSTOM_RATES = 'GET_USERS_WITH_CUSTOM_RATES';
export const GET_USERS_WITH_CUSTOM_RATES_SUCCESS = 'GET_USERS_WITH_CUSTOM_RATES_SUCCESS';
export const GET_USERS_WITH_CUSTOM_RATES_ERROR = 'GET_USERS_WITH_CUSTOM_RATES_ERROR';

export const GET_CUSTOM_RATES_FOR_USER = 'GET_CUSTOM_RATES_FOR_USER';
export const GET_CUSTOM_RATES_FOR_USER_SUCCESS = 'GET_CUSTOM_RATES_FOR_USER_SUCCESS';
export const GET_CUSTOM_RATES_FOR_USER_ERROR = 'GET_CUSTOM_RATES_FOR_USER_ERROR';

export const GET_SERVICES_LIST = 'GET_SERVICES_LIST';
export const GET_SERVICES_LIST_SUCCESS = 'GET_SERVICES_LIST_SUCCESS';
export const GET_SERVICES_LIST_ERROR = 'GET_SERVICES_LIST_ERROR';

export const UPDATE_CUSTOM_RATES = 'UPDATE_CUSTOM_RATES';
export const UPDATE_CUSTOM_RATES_SUCCESS = 'UPDATE_CUSTOM_RATES_SUCCESS';
export const UPDATE_CUSTOM_RATES_ERROR = 'UPDATE_CUSTOM_RATES_ERROR';

export const GET_EXPORT_LIST = 'GET_EXPORT_LIST';
export const GET_EXPORT_LIST_SUCCESS = 'GET_EXPORT_LIST_SUCCESS';
export const GET_EXPORT_LIST_ERROR = 'GET_EXPORT_LIST_ERROR';

export const MAKE_EXPORT = 'MAKE_EXPORT';
export const MAKE_EXPORT_SUCCESS = 'MAKE_EXPORT_SUCCESS';
export const MAKE_EXPORT_ERROR = 'MAKE_EXPORT_ERROR';

export const GET_ACTIVITY_LOG = 'GET_ACTIVITY_LOG';
export const GET_ACTIVITY_LOG_SUCCESS = 'GET_ACTIVITY_LOG_SUCCESS';
export const GET_ACTIVITY_LOG_ERROR = 'GET_ACTIVITY_LOG_ERROR';

export const GET_SIGNIN_HISTORY = 'GET_SIGNIN_HISTORY';
export const GET_SIGNIN_HISTORY_SUCCESS = 'GET_SIGNIN_HISTORY_SUCCESS';
export const GET_SIGNIN_HISTORY_ERROR = 'GET_SIGNIN_HISTORY_ERROR';
