export const GET_NAVBAR = 'GET_NAVBAR';
export const GET_NAVBAR_SUCCESS = 'GET_NAVBAR_SUCCESS';
export const GET_NAVBAR_ERROR = 'GET_NAVBAR_ERROR';

export const SET_FIRST_RENDERING = 'SET_FIRST_RENDERING';
