export const CLEAR_REFILL_STATE = 'CLEAR_REFILL_STATE';

export const GET_REFILL_LIST = 'GET_REFILL_LIST';
export const GET_REFILL_LIST_SUCCESS = 'GET_REFILL_LIST_SUCCESS';
export const GET_REFILL_LIST_ERROR = 'GET_REFILL_LIST_ERROR';

export const GET_REFILL_CONFIG = 'GET_REFILL_CONFIG';
export const GET_REFILL_CONFIG_SUCCESS = 'GET_REFILL_CONFIG_SUCCESS';
export const GET_REFILL_CONFIG_ERROR = 'GET_REFILL_CONFIG_ERROR';

export const GET_REFILL_MODES = 'GET_REFILL_MODES';
export const GET_REFILL_MODES_SUCCESS = 'GET_REFILL_MODES_SUCCESS';
export const GET_REFILL_MODES_ERROR = 'GET_REFILL_MODES_ERROR';

export const GET_REFILL_SERVICES = 'GET_REFILL_SERVICES';
export const GET_REFILL_SERVICES_SUCCESS = 'GET_REFILL_SERVICES_SUCCESS';
export const GET_REFILL_SERVICES_ERROR = 'GET_REFILL_SERVICES_ERROR';

export const VIEW_REFILL_TASK = 'VIEW_REFILL_TASK';
export const VIEW_REFILL_TASK_SUCCESS = 'VIEW_REFILL_TASK_SUCCESS';
export const VIEW_REFILL_TASK_ERROR = 'VIEW_REFILL_TASK_ERROR';

export const DETAILS_SUPER_REFILL = 'DETAILS_SUPER_REFILL';
export const DETAILS_SUPER_REFILL_SUCCESS = 'DETAILS_SUPER_REFILL_SUCCESS';
export const DETAILS_SUPER_REFILL_ERROR = 'DETAILS_SUPER_REFILL_ERROR';

export const RESEND_REFILL_TASK = 'RESEND_REFILL_TASK';
export const RESEND_REFILL_TASK_SUCCESS = 'RESEND_REFILL_TASK_SUCCESS';
export const RESEND_REFILL_TASK_ERROR = 'RESEND_REFILL_TASK_ERROR';

export const CANCEL_REFILL_TASK = 'CANCEL_REFILL_TASK';
export const CANCEL_REFILL_TASK_SUCCESS = 'CANCEL_REFILL_TASK_SUCCESS';
export const CANCEL_REFILL_TASK_ERROR = 'CANCEL_REFILL_TASK_ERROR';

export const CHANGE_REFILL_TASK_STATUS = 'CHANGE_REFILL_TASK_STATUS';
export const CHANGE_REFILL_TASK_STATUS_SUCCESS = 'CHANGE_REFILL_TASK_STATUS_SUCCESS';
export const CHANGE_REFILL_TASK_STATUS_ERROR = 'CHANGE_REFILL_TASK_STATUS_ERROR';

export const BULK_UPDATE_STATUS_REFILL = 'BULK_UPDATE_STATUS_REFILL';
export const BULK_UPDATE_STATUS_REFILL_SUCCESS = 'BULK_UPDATE_STATUS_REFILL_SUCCESS';
export const BULK_UPDATE_STATUS_REFILL_ERROR = 'BULK_UPDATE_STATUS_REFILL_ERROR';

export const BULK_RESEND_REFILL_TASKS = 'BULK_RESEND_REFILL_TASKS';
export const BULK_RESEND_REFILL_TASKS_SUCCESS = 'BULK_RESEND_REFILL_TASKS_SUCCESS';
export const BULK_RESEND_REFILL_TASKS_ERROR = 'BULK_RESEND_REFILL_TASKS_ERROR';

export const BULK_CANCEL_REFILL_TASKS = 'BULK_CANCEL_REFILL_TASKS';
export const BULK_CANCEL_REFILL_TASKS_SUCCESS = 'BULK_CANCEL_REFILL_TASKS_SUCCESS';
export const BULK_CANCEL_REFILL_TASKS_ERROR = 'BULK_CANCEL_REFILL_TASKS_ERROR';
