export const CLEAR_ORDERS_STATE = 'CLEAR_ORDERS_STATE';

export const GET_ORDERS_LIST = 'GET_ORDERS_LIST';
export const GET_ORDERS_LIST_SUCCESS = 'GET_ORDERS_LIST_SUCCESS';
export const GET_ORDERS_LIST_ERROR = 'GET_ORDERS_LIST_ERROR';

export const GET_ORDERS_CONFIG = 'GET_ORDERS_CONFIG';
export const GET_ORDERS_CONFIG_SUCCESS = 'GET_ORDERS_CONFIG_SUCCESS';
export const GET_ORDERS_CONFIG_ERROR = 'GET_ORDERS_CONFIG_ERROR';

export const CHANGE_ORDER_STATUS = 'CHANGE_ORDER_STATUS';
export const CHANGE_ORDER_STATUS_SUCCESS = 'CHANGE_ORDER_STATUS_SUCCESS';
export const CHANGE_ORDER_STATUS_ERROR = 'CHANGE_ORDER_STATUS_ERROR';

export const CANCEL_ORDER = 'CANCEL_ORDER';
export const CANCEL_ORDER_SUCCESS = 'CANCEL_ORDER_SUCCESS';
export const CANCEL_ORDER_ERROR = 'CANCEL_ORDER_ERROR';

export const RESEND_ORDER = 'RESEND_ORDER';
export const RESEND_ORDER_SUCCESS = 'RESEND_ORDER_SUCCESS';
export const RESEND_ORDER_ERROR = 'RESEND_ORDER_ERROR';

export const REFILL_ORDER = 'REFILL_ORDER';
export const REFILL_ORDER_SUCCESS = 'REFILL_ORDER_SUCCESS';
export const REFILL_ORDER_ERROR = 'REFILL_ORDER_ERROR';

export const SET_ORDER_PARTIAL = 'SET_ORDER_PARTIAL';
export const SET_ORDER_PARTIAL_SUCCESS = 'SET_ORDER_PARTIAL_SUCCESS';
export const SET_ORDER_PARTIAL_ERROR = 'SET_ORDER_PARTIAL_ERROR';

export const SET_ORDER_REMAINS = 'SET_ORDER_REMAINS';
export const SET_ORDER_REMAINS_SUCCESS = 'SET_ORDER_REMAINS_SUCCESS';
export const SET_ORDER_REMAINS_ERROR = 'SET_ORDER_REMAINS_ERROR';

export const GET_ORDER_DETAILS = 'GET_ORDER_DETAILS';
export const GET_ORDER_DETAILS_SUCCESS = 'GET_ORDER_DETAILS_SUCCESS';
export const GET_ORDER_DETAILS_ERROR = 'GET_ORDER_DETAILS_ERROR';

export const CHANGE_ORDER_LINK = 'CHANGE_ORDER_LINK';
export const CHANGE_ORDER_LINK_SUCCESS = 'CHANGE_ORDER_LINK_SUCCESS';
export const CHANGE_ORDER_LINK_ERROR = 'CHANGE_ORDER_LINK_ERROR';

export const GET_ORDER_SEND_INFO = 'GET_ORDER_SEND_INFO';
export const GET_ORDER_SEND_INFO_SUCCESS = 'GET_ORDER_SEND_INFO_SUCCESS';
export const GET_ORDER_SEND_INFO_ERROR = 'GET_ORDER_SEND_INFO_ERROR';

export const BULK_ORDERS_STATUS = 'BULK_ORDERS_STATUS';
export const BULK_ORDERS_STATUS_SUCCESS = 'BULK_ORDERS_STATUS_SUCCESS';
export const BULK_ORDERS_STATUS_ERROR = 'BULK_ORDERS_STATUS_ERROR';

export const GET_USERS_LIST_SEARCH = 'GET_USERS_LIST_SEARCH';
export const GET_USERS_LIST_SEARCH_SUCCESS = 'GET_USERS_LIST_SEARCH_SUCCESS';
export const GET_USERS_LIST_SEARCH_ERROR = 'GET_USERS_LIST_SEARCH_ERROR';
